---
name: Check links in README.md

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: docker://dkhamsing/awesome_bot:latest
      with:
        args: /github/workspace/README.md  --allow 403,418,429,500,501,502,503,504,509,521 --allow-dupe --request-delay 1 --allow-redirect --white-list https://ipfs.io,slideshare
